package project_skeleton;

import java.io.*;
import java.net.*;
import java.security.*;

import javax.crypto.*;

public class CipherServer
{
	public static void main(String[] args) throws Exception 
	{
		int port = 7999;
		ServerSocket server = new ServerSocket(port);
		Socket s = server.accept();

		// YOU NEED TO DO THESE STEPS:
		// -Read the key from the file generated by the client.
		
		ObjectInputStream in = new ObjectInputStream(new FileInputStream("project_skeleton/KeyFile.txt"));
		Key k = (Key) in.readObject();
		in.close();
				
		// -Use the key to decrypt the incoming message from socket s.		
		
		Cipher cipher = Cipher.getInstance("DES/ECB/PKCS5Padding");
		cipher.init(Cipher.DECRYPT_MODE, k);
		CipherInputStream cis = new CipherInputStream(s.getInputStream(), cipher);
		
		BufferedReader br = new BufferedReader(new InputStreamReader(cis));
		String message = br.readLine();
		br.close();
		
		// -Print out the decrypt String to see if it matches the orignal message.
		
		System.out.println(message);
		
		if (message.equals("The quick brown fox jumps over the lazy dog."))
			  System.out.println("Client logged in ^.^");
			else
			  System.out.println("Client failed to log in = =#");
		
		s.close();

	}
}